default_language_version:
  python: python3.13

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.22.1" # replace with latest tag on GitHub
    hooks:
      - id: django-upgrade
        args: [--target-version, "5.1"] # Replace with Django version
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.7.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/thibaudcolas/curlylint
    rev: v0.13.1
    hooks:
      - id: curlylint
        exclude: 'templates/snippets/timetable_search\.html'
  - repo: https://github.com/adamchainz/djade-pre-commit
    rev: "1.3.0"
    hooks:
    -   id: djade
        args: [--target-version, "5.1"]
  - repo: https://github.com/rtts/djhtml
    rev: 3.0.7
    hooks:
      - id: djhtml
        args:
          - --tabwidth=2
        exclude: markdown_editor.html
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or:
          - css
          - xml
        additional_dependencies:
          - prettier@2.5.1
          - "@prettier/plugin-xml@1.2.0"
